version: 1.{build}

before_build:
    - gem query -i -n builder || gem install builder

after_build:
    - del _build\prod\lib\monitor\.rebar3\erlcinfo
    - del _build\prod\lib\sysmo\.rebar3\erlcinfo
    - del _build\prod\lib\j_server\.rebar3\erlcinfo
    - del _build\default\lib\ranch\.rebar3\erlcinfo
    - del _build\default\lib\monitor\.rebar3\erlcinfo
    - del _build\default\lib\cowboy\.rebar3\erlcinfo
    - del _build\default\lib\supercast\.rebar3\erlcinfo
    - del _build\default\lib\cowlib\.rebar3\erlcinfo
    - del _build\default\lib\sysmo\.rebar3\erlcinfo
    - del _build\default\lib\jsx\.rebar3\erlcinfo
    - del _build\default\lib\j_server\.rebar3\erlcinfo
    - .\apps\j_server\priv\jserver\gradlew.bat --stop
    - del C:\Users\appveyor\.gradle\caches\modules-2\modules-2.lock

build_script:
    - rake release

cache:
  - C:\Users\appveyor\.gradle\caches\
  - C:\Users\appveyor\.gradle\wrapper\
  - C:\Ruby193\lib\ruby\gems\
  - .\build\default\lib
  - .\build\prod\lib

