version: 1.{build}

platform:
    - x64
    - Win32

before_build:
    - gem query -i -n builder || gem install builder
    - git submodule update --init

build_script:
    - rake pack

artifacts:
    - path: _build\Sysmo-Core-*.exe
    - path: _build\__installer-*.msi

deploy:
    release: CURRENT
    description: 'Automatic Sysmo Core release deployment'
    provider: GitHub
    auth_token:
        secure: JbU57GgB5EBgwKdw4kTc2LTimc85On9dVaiCAbnqIPRbQxEs6KFEBOHxh8eFuqqD
    artifact: /Sysmo-Core-.*\.exe/, /__installer-.*\.msi/
    force_update: true
    draft: true
    prerelease: false
    on:
        branch: master
        appveyor_repo_tag: false


cache:
  - C:\Ruby193\lib\ruby\gems\
  - C:\Users\appveyor\SYSMO_CORE_RESSOURCES\

