version: 1.{build}

platform:
    - x64
    - Win32

before_build:
    - gem query -i -n builder || gem install builder
    - git submodule update --init

build_script:
    - rake release

cache:
  - C:\Ruby193\lib\ruby\gems\

