language: erlang

otp_release:
  - 17.1

sudo: false

install: "gem query -i -n builder || gem install builder"

script: "rake release"

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -f deps/*/.rebar/erlcinfo  .rebar/erlcinfo

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.gem/
    - deps/
