version: 1.{build}
branches:
    only:
        - master

build_script:
    - gem query -i -n builder || gem install builder
    - rake release
    - .\apps\j_server\priv\jserver\gradlew.bat --stop


cache:
  - C:\Users\appveyor\.gradle\caches\
  - C:\Users\appveyor\.gradle\wrapper\
  - C:\Ruby193\lib\ruby\gems\
  - deps

